"""
Complete SendGrid Email Connector
==================================
"""

import asyncio
from typing import Dict, Any, List, Optional
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail, Email, To, Content, Attachment
import base64

from src.core.config import get_settings


settings = get_settings()


class EmailConnector:
    """Production SendGrid email connector."""
    
    def __init__(self):
        self.api_key = settings.sendgrid_api_key
        self.from_email = settings.email_from
        
        if not self.api_key:
            raise ValueError("SENDGRID_API_KEY required")
        
        self.client = SendGridAPIClient(self.api_key)
    
    async def send(
        self,
        to: str | List[str],
        subject: str,
        body_text: Optional[str] = None,
        body_html: Optional[str] = None,
        attachments: Optional[List[str]] = None,
        template_id: Optional[str] = None,
        template_data: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Send email via SendGrid.
        
        Args:
            to: Recipient email(s)
            subject: Email subject
            body_text: Plain text body
            body_html: HTML body
            attachments: List of file paths to attach
            template_id: SendGrid template ID
            template_data: Data for template variables
            
        Returns:
            Send result with message ID
        """
        # Convert single email to list
        if isinstance(to, str):
            to = [to]
        
        # Build message
        message = Mail(
            from_email=self.from_email,
            to_emails=to,
            subject=subject,
        )
        
        # Add content
        if body_text:
            message.content = Content("text/plain", body_text)
        
        if body_html:
            message.content = Content("text/html", body_html)
        
        # Add template
        if template_id:
            message.template_id = template_id
            if template_data:
                message.dynamic_template_data = template_data
        
        # Add attachments
        if attachments:
            for file_path in attachments:
                with open(file_path, 'rb') as f:
                    file_data = f.read()
                
                encoded = base64.b64encode(file_data).decode()
                
                attachment = Attachment()
                attachment.file_content = encoded
                attachment.file_name = file_path.split('/')[-1]
                attachment.disposition = "attachment"
                
                message.attachment = attachment
        
        # Send
        try:
            response = self.client.send(message)
            
            return {
                "success": True,
                "status_code": response.status_code,
                "message_id": response.headers.get("X-Message-Id"),
                "to": to,
                "subject": subject,
            }
        
        except Exception as e:
            return {
                "success": False,
                "error": str(e),
            }
    
    async def send_research_complete(
        self,
        to: str,
        project_name: str,
        findings_summary: str,
        project_url: str,
    ) -> Dict[str, Any]:
        """Send 'research complete' notification."""
        
        html_body = f"""
        <html>
        <body style="font-family: Arial, sans-serif;">
            <h2 style="color: #2563eb;">Research Complete: {project_name}</h2>
            
            <p>Your autonomous research has been completed!</p>
            
            <div style="background: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0;">
                <h3>Key Findings:</h3>
                <p>{findings_summary}</p>
            </div>
            
            <p>
                <a href="{project_url}" 
                   style="background: #2563eb; color: white; padding: 12px 24px; 
                          text-decoration: none; border-radius: 6px; display: inline-block;">
                    View Full Results
                </a>
            </p>
            
            <p style="color: #6b7280; font-size: 14px; margin-top: 30px;">
                Generated by Agentic Research AI
            </p>
        </body>
        </html>
        """
        
        return await self.send(
            to=to,
            subject=f"✅ Research Complete: {project_name}",
            body_html=html_body,
        )
    
    async def send_team_invitation(
        self,
        to: str,
        inviter_name: str,
        workspace_name: str,
        invitation_url: str,
    ) -> Dict[str, Any]:
        """Send team invitation email."""
        
        html_body = f"""
        <html>
        <body style="font-family: Arial, sans-serif;">
            <h2 style="color: #2563eb;">You've been invited to join a workspace!</h2>
            
            <p><strong>{inviter_name}</strong> has invited you to join <strong>{workspace_name}</strong>.</p>
            
            <p>
                <a href="{invitation_url}" 
                   style="background: #2563eb; color: white; padding: 12px 24px; 
                          text-decoration: none; border-radius: 6px; display: inline-block;">
                    Accept Invitation
                </a>
            </p>
            
            <p style="color: #6b7280; font-size: 14px; margin-top: 30px;">
                If you didn't expect this invitation, you can safely ignore this email.
            </p>
        </body>
        </html>
        """
        
        return await self.send(
            to=to,
            subject=f"{inviter_name} invited you to {workspace_name}",
            body_html=html_body,
        )
    
    async def send_bulk(
        self,
        recipients: List[Dict[str, str]],  # [{"email": "...", "data": {...}}]
        template_id: str,
    ) -> Dict[str, Any]:
        """
        Send bulk emails with personalization.
        
        Args:
            recipients: List of {"email": "...", "data": {...}}
            template_id: SendGrid template ID
            
        Returns:
            Bulk send result
        """
        personalizations = []
        
        for recipient in recipients:
            personalizations.append({
                "to": [{"email": recipient["email"]}],
                "dynamic_template_data": recipient.get("data", {}),
            })
        
        message = Mail(
            from_email=self.from_email,
        )
        message.template_id = template_id
        message.personalizations = personalizations
        
        try:
            response = self.client.send(message)
            
            return {
                "success": True,
                "status_code": response.status_code,
                "recipient_count": len(recipients),
            }
        
        except Exception as e:
            return {
                "success": False,
                "error": str(e),
            }


# Singleton
_email_connector: Optional[EmailConnector] = None


def get_email_connector() -> EmailConnector:
    """Get email connector singleton."""
    global _email_connector
    
    if _email_connector is None:
        _email_connector = EmailConnector()
    
    return _email_connector
